#version: '3'
#
#services:
#  postgres:
#    image: postgres:12.3
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=booking
#
#  task-management-system:
#    container_name: "tms-app"
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
