server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsm
    username: postgres
    password: postgres
    hikari:
      schema: booking
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS tsm
      connection-timeout: 10000
  application:
    name: task-management-system
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
