server:
    port: 80
spring:
  datasource:
    url: jdbc:h2:mem:tms
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
  liquibase:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
#server:
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:ssl/taskssl.pfx
#    key-store-password: rootroot

