name: Deploy Docker container to Server

on:
  push:
    branches:
      - main  # Триггер срабатывает при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t tsm-container .

      - name: Save Docker image to a tar file
        run: docker save -o tsm-container.tar tsm-container

      - name: Copy Docker image to server via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SHH_HOST }}
          username: ${{ secrets.SHH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "tsm-container.tar"
          target: "/home/${{ secrets.WORK_DIR }}/my-container.tar"

      - name: Deploy Docker container on server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SHH_HOST }}
          username: ${{ secrets.SHH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i /home/${{ secrets.WORK_DIR }}/my-container.tar
            docker run -d -p 80:80 my-container